name: package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Install packages
        # The Github's Ubuntu images since 20211122.1 are broken
        # https://github.com/actions/virtual-environments/issues/4589
        run: |
          set -xeu -o pipefail
          sudo dpkg --add-architecture i386
          sudo apt-get -qq update
          sudo apt-get -qq install -o=Dpkg::Use-Pty=0 -y --allow-downgrades libpcre2-8-0=10.34-7
          sudo apt-get -qq install -o=Dpkg::Use-Pty=0 -y p7zip wine-stable wine32
          wineboot

      - name: Package
        run: ./extra/package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: sets
          path: sets/*.dat

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: sets/*.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
